name: Scan Container Images

on:
  pull_request:
      branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CrowdStrike Container Image Scan
        uses: crowdstrike/container-image-scan-action@v1.1.0
        with:
          falcon_client_id: "${{ secrets.FALCON_CLIENT_ID }}"
          container_repository: docker.io/library/busybox
        env:
          FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
